services:
  gateway:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./gateway:/app # live-mount code into container
  gateway-tests:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    command: pytest -v
    volumes:
      - ./gateway:/app
    environment:
      - PYTHONPATH=/app
      - AMQP_URL=amqp://user:pass@rabbitmq:5672
    depends_on:
      - rabbitmq

  aggregator:
    command: sh -c "pip install watchfiles && watchfiles --filter python 'python worker.py'"
    volumes:
      - ./aggregator:/app
  aggregator-tests:
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    command: pytest -v
    volumes:
      - ./aggregator:/app
    environment:
      - PYTHONPATH=/app

  client:
    volumes:
      - ./client/index.html:/usr/share/nginx/html/index.html

  notifications:
    command: sh -c "pip install watchfiles && watchfiles --filter python 'python notifier.py'"
    volumes:
      - ./notifications:/app
  notifications-tests:
    build:
      context: .
      dockerfile: notifications/Dockerfile
    command: pytest -v
    volumes:
      - ./notifications:/app
    environment:
      - PYTHONPATH=/app
  storage-test:
    build:
      context: .
      dockerfile: storage/Dockerfile
      args:
        ENV: dev
    volumes:
      - ./storage:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=postgresql+psycopg://app:app@postgres:5432/oneapi
      - PYTHONPATH=/app
      - TESTCONTAINERS_RYUK_DISABLED=true
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
