[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oneapi-monorepo"
version = "0.0.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["storage*"]
